# Generated by Django 3.2.9 on 2022-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='chunk_size',
            field=models.IntegerField(verbose_name='分片的大小'),
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='status',
            field=models.IntegerField(verbose_name='状态,0-上传中,1-上传成功,2-上传失败,3-待开始'),
        ),
    ]
